---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре (разбила на 2 тест-кейса)
  - Пользователь должен иметь возможность фильтровать товары (разбила на 4 тест-кейса)
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
  - Пользователь должен иметь возможность сбрасывать фильтры
  - При смене языка с английского на русский должны переводиться все тексты на сайте (за исключением названий брендов) 
  - При перезагрузке страницы сайт должен оставаться на выбранном ранее языке
  - Итоговая стоимость товаров в корзине должна высчитываться без ошибок
  - Пользователь должен иметь возможность очистить всю корзину одним действием
  - Пользователь должен иметь возможность выборочно удалять товары из корзины
  - Пользователь должен иметь возможность менять колчество товаров в корзине (увеличивать/уменьшать)
  - Пользователь должен иметь возможность открыть страницу добавленного в корзину товара не выходя из корзины


  
