---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
  - Пользователь должен иметь возможность сбрасывать фильтры без перезагрузки страницы
  - При смене языка с английского на русский, описания товаров также должны переводиться на русский
  - При смене языка с английского на русский, названия товаров, которые не являются названием бренда, также должны переводиться на русский
  - При перезагрузке страницы сайт должен оставаться на выбранном ранее языке
  - При фильтрации товаров по категориям должны появляться все существующие на данный момент категории
  - Поиск товаров должен осуществляться по всем товарам, которые есть на сайте
  - Описание характеристик товара и цены должны быть представлены в удобном для восприятия виде
  - При переходе из одного раздела в другой страница не должна перезагружаться
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее

  
